# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlotDate', models.DateField()),
                ('SlotTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('BookingId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('EmailAddress', models.EmailField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='bookingslots',
            name='BookingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.UserBooking'),
        ),
    ]
